---
sidebar: sidebar 
permalink: faq-upgrade-health-checker.html 
keywords: upgrade, health, checker, faq, frequently asked questions, frequently asked questions about upgrade health checker 
summary: '업그레이드 상태 점검 도구에 대한 자주 묻는 질문(FAQ).' 
---
= 업그레이드 상태 점검 도구 FAQ
:hardbreaks:
:allow-uri-read: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
업그레이드 상태 점검 도구에 대한 자주 묻는 질문(FAQ).



== Upgrade Health Checker는 Upgrade Advisor와 어떻게 다릅니까?

Upgrade Health Checker는 규모가 크거나 복잡한 환경, 인터넷 접속이 제한적인 환경, 또는 기존 자동화 및 오케스트레이션 프레임워크를 사용하는 사용자에게 적합한 온프레미스 도구입니다. Upgrade Advisor는 클라우드 기반의 사용자 인터페이스 중심 환경을 선호하는 소규모 환경의 사용자에게 적합합니다.

link:learn-about-upgrade-health-checker.html["업그레이드 상태 점검기"] 및 link:https://docs.netapp.com/us-en/active-iq/upgrade_advisor_overview.html["업그레이드 어드바이저"^]에 대해 자세히 알아보고 필요에 가장 적합한 도구를 결정할 수 있습니다.



== Upgrade Health Checker 보고서에는 어떤 정보가 포함되어 있습니까?

업그레이드 상태 점검 보고서는 ONTAP 클러스터를 업그레이드하기 전에 해결해야 할 잠재적인 차단 요소 및 경고, 클러스터와 관련된 위험, 그리고 업그레이드할 ONTAP 버전의 새로운 기능 및 개선 사항에 대한 자세한 정보를 제공합니다.



== Upgrade Health Checker는 인터넷 연결 없이 사용할 수 있습니까?

Upgrade Health Checker를 실행하는 데 인터넷 연결이 필요하지 않습니다. ONTAP 클러스터의 현재 구성 데이터를 사용하여 현장에서 업그레이드 계획 및 보고서를 생성합니다.

단, 자동 도구 업데이트를 위해서는 인터넷 연결이 필요합니다. 인터넷 연결이 불가능한 환경에서는 link:https://console.netapp.com/automationHub["NetApp Console 자동화 허브"]의 Upgrade Health Checker 타일에서 최신 버전의 도구를 수동으로 다운로드할 수 있습니다.



== Upgrade Health Checker는 어떤 ONTAP 버전을 지원합니까?

업그레이드 상태 검사기는 ONTAP 9.11.1 이상으로의 업그레이드를 지원합니다.
