---
sidebar: sidebarU 
permalink: whats-new.html 
keywords: upgrade, health, checker, whats new, release, notes 
summary: 이 문서 사이트의 새로운 소식을 알아보세요. 
---
= Upgrade Health Checker의 새로운 기능
:hardbreaks:
:allow-uri-read: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Upgrade Health Checker(UHC)의 새로운 기능을 알아보십시오. link:https://console.netapp.com/automationHub["NetApp Console 자동화 허브"^]에서 Upgrade Health Checker 타일로 이동하여 최신 Upgrade Health Checker 다운로드 파일을 확인하면 추가 개선 정보를 찾을 수 있습니다.



== 2026년 6월 11일

Upgrade Health Checker 문서의 이번 업데이트에는 다음과 같은 기능이 포함되어 있습니다.

* UHC는 보고서를 받은 편지함으로 직접 전달하는 것을 지원합니다.
+
link:setup-email-upgrade-health-checker.html["이메일로 업그레이드 상태 점검 보고서 받기"].

*  `--dashboard` 매개변수를 도입하여 클러스터에 연결하지 않고 `<runs>/dashboard/index.html`에서 기존 실행으로부터 대시보드를 재생성합니다. 최근에 액세스한 모든 클러스터의 상태에 대한 개략적인 개요를 제공합니다.
+
link:dashboard-upgrade-health-checker.html["업그레이드 상태 점검 대시보드"], link:upgrade-health-checker-input-parameters.html#dashboard["대시보드 파라미터"].

* 새로운 유지 관리, 문제 해결 및 FAQ 섹션을 소개합니다.
+
** Upgrade Health Checker를 유지 관리하려면 정기적으로 업데이트를 확인하고, 로그를 모니터링하여 반복되는 문제가 있는지 확인하고, 도구가 사용 환경에 맞게 올바르게 구성되었는지 확인하십시오.
+
link:maintain-upgrade-health-checker.html["업그레이드 상태 검사기 유지 관리"].

** 일반적인 업그레이드 상태 점검 문제를 해결하고 ONTAP 업그레이드 계획을 차단할 수 있는 오류를 해결하십시오.
+
link:troubleshoot-upgrade-health-checker.html["업그레이드 상태 점검 도구 문제 해결"].

** 업그레이드 상태 점검 도구에 대한 자주 묻는 질문(FAQ).
+
link:faq-upgrade-health-checker.html["업그레이드 상태 점검 도구 FAQ"].







== 2026년 4월 15일

Upgrade Health Checker 문서의 이번 업데이트에는 다음과 같은 기능이 포함되어 있습니다.

* UHC가 자동 업데이트 기능을 작동시키려면 새로운 엔드포인트(+https://api.activeiq.netapp.com+)에 대한 액세스 권한이 필요합니다.
+
link:set-up-upgrade-health-checker.html["Upgrade Health Checker를 다운로드하고 설정합니다"].

* UHC는 이제 HTML(사람이 읽을 수 있음) 및 JSON(기계가 읽을 수 있음) 형식을 보완하는 새로운 보고서 형식(.XLSX - 사람이 편집 가능)을 제공합니다.
+
link:generate-report-upgrade-health-checker.html["ONTAP 업그레이드 보고서를 생성합니다"].

+
link:automate-report-upgrade-health-checker.html["Upgrade Health Checker를 사용하여 업그레이드 계획 생성 자동화"].





== 2026년 2월 13일

Upgrade Health Checker는 성공적인 ONTAP 업그레이드를 완료할 수 있도록 포괄적인 온사이트 보고서를 생성하는 새로운 솔루션을 제공합니다. 기존 자동화 및 오케스트레이션 프레임워크와 함께 사용하여 단일 또는 다중 클러스터를 업그레이드할 때 효율성을 향상시킬 수 있습니다. Upgrade Health Checker는 ONTAP 9.11.1 이상으로의 업그레이드를 지원합니다.

link:learn-about-upgrade-health-checker.html["Upgrade Health Checker에 대해 자세히 알아보십시오"].
