---
sidebar: sidebar 
permalink: whats-new.html 
keywords: upgrade, health, checker, whats new, release, notes 
summary: 이 문서 사이트의 새로운 소식을 알아보세요. 
---
= Upgrade Health Checker의 새로운 기능
:hardbreaks:
:allow-uri-read: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Upgrade Health Checker의 새로운 기능을 알아보십시오. link:https://console.netapp.com/automationHub["NetApp Console 자동화 허브"^]에서 Upgrade Health Checker 타일로 이동하여 최신 Upgrade Health Checker 다운로드 파일을 확인하면 추가 개선 정보를 찾을 수 있습니다.



== 2026년 4월 15일

Upgrade Health Checker 문서의 이번 업데이트에는 다음과 같은 기능이 포함되어 있습니다.

* UHC가 자동 업데이트 기능을 작동시키려면 새로운 엔드포인트(+https://api.activeiq.netapp.com+)에 대한 액세스 권한이 필요합니다.
+
link:set-up-upgrade-health-checker.html["Upgrade Health Checker를 다운로드하고 설정합니다"].

* UHC는 이제 HTML(사람이 읽을 수 있음) 및 JSON(기계가 읽을 수 있음) 형식을 보완하는 새로운 보고서 형식(.XLSX - 사람이 편집 가능)을 제공합니다.
+
link:generate-report-upgrade-health-checker.html["ONTAP 업그레이드 보고서를 생성합니다"].

+
link:automate-report-upgrade-health-checker.html["Upgrade Health Checker를 사용하여 업그레이드 계획 생성 자동화"].





== 2026년 2월 13일

Upgrade Health Checker는 성공적인 ONTAP 업그레이드를 완료할 수 있도록 포괄적인 온사이트 보고서를 생성하는 새로운 솔루션을 제공합니다. 기존 자동화 및 오케스트레이션 프레임워크와 함께 사용하여 단일 또는 다중 클러스터를 업그레이드할 때 효율성을 향상시킬 수 있습니다. Upgrade Health Checker는 ONTAP 9.11.1 이상으로의 업그레이드를 지원합니다.

link:learn-about-upgrade-health-checker.html["Upgrade Health Checker에 대해 자세히 알아보십시오"].
